apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2-ml-service
  template:
    metadata:
      labels:
        app: m2-ml-service
    spec:
      containers:
        - name: m2-ml-service
          image: fatmaboubakri/piprojet-ml-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
